/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:728a4e95-d158-4f22-a784-1dd41373d773",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_zHBKwV2gV",
    "aws_user_pools_web_client_id": "2e1mtgbdl7n9m32egm3iqslpr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xcpvmlifcnepfezvrek6mq7iqa.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-44qnbffmpvbypixz4zni7oemvi",
    "aws_user_files_s3_bucket": "cwimages153118-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
